# Generated by Django 4.2.11 on 2024-03-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('ES', models.IntegerField(default=0)),
                ('EF', models.IntegerField()),
                ('LS', models.FloatField(default=float("inf"))),
                ('LF', models.FloatField(default=float("inf"))),
                ('slack', models.FloatField(default=0)),
                ('critical', models.CharField(blank=True, max_length=3)),
                ('predecessors', models.ManyToManyField(to='cpmApp.task')),
            ],
        ),
    ]
