# Generated by Django 4.2.11 on 2024-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='EF',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='ES',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='LF',
            field=models.FloatField(default=99999999999, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='LS',
            field=models.FloatField(default=99999999999, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='critical',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='slack',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
