# Generated by Django 4.2.11 on 2024-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0002_alter_task_ef_alter_task_es_alter_task_lf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='EF',
            field=models.IntegerField(default=models.IntegerField(), editable=False),
        ),
    ]
