# Generated by Django 4.2.11 on 2024-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0003_alter_task_ef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='LF',
            field=models.FloatField(default=999999, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='LS',
            field=models.FloatField(default=999999, editable=False),
        ),
    ]
