# Generated by Django 4.2.11 on 2024-04-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0006_remove_task_predecessors_task_succ_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='EF',
            field=models.IntegerField(default=models.CharField(max_length=9), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.CharField(max_length=9),
        ),
    ]
