# Generated by Django 4.2.11 on 2024-04-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0007_alter_task_ef_alter_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='succ_left',
        ),
        migrations.RemoveField(
            model_name='task',
            name='succ_right',
        ),
        migrations.AddField(
            model_name='task',
            name='next_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_left', to='cpmApp.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='next_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_right', to='cpmApp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='EF',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='LF',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='LS',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='critical',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='slack',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
