# Generated by Django 4.2.11 on 2024-04-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0008_remove_task_succ_left_remove_task_succ_right_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ES', models.FloatField(default=0.0)),
                ('EF', models.FloatField(default=0.0)),
                ('LS', models.FloatField(default=0.0)),
                ('LF', models.FloatField(default=0.0)),
                ('isCritical', models.BooleanField(default=False)),
                ('isStart', models.BooleanField(default=False)),
                ('isEnd', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='EF',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ES',
        ),
        migrations.RemoveField(
            model_name='task',
            name='LF',
        ),
        migrations.RemoveField(
            model_name='task',
            name='LS',
        ),
        migrations.RemoveField(
            model_name='task',
            name='critical',
        ),
        migrations.RemoveField(
            model_name='task',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='next_left',
        ),
        migrations.RemoveField(
            model_name='task',
            name='next_right',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slack',
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='task',
            name='endActivity',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='end_activities', to='cpmApp.activity'),
        ),
        migrations.AddField(
            model_name='task',
            name='startActivity',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='start_activities', to='cpmApp.activity'),
        ),
    ]
