# Generated by Django 4.2.11 on 2024-04-21 15:18

import cpmApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0009_activity_remove_task_ef_remove_task_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endActivity',
            field=models.BooleanField(default=False, verbose_name=cpmApp.models.Activity),
        ),
        migrations.AlterField(
            model_name='task',
            name='startActivity',
            field=models.BooleanField(default=False, verbose_name=cpmApp.models.Activity),
        ),
    ]
