# Generated by Django 4.2.11 on 2024-04-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0010_alter_task_endactivity_alter_task_startactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_tasks', to='cpmApp.activity'),
        ),
        migrations.AlterField(
            model_name='task',
            name='startActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_tasks', to='cpmApp.activity'),
        ),
    ]
