# Generated by Django 4.2.11 on 2024-04-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0015_alter_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='endActivity',
            new_name='end_activity',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='startActivity',
            new_name='start_activity',
        ),
    ]
