# Generated by Django 4.2.11 on 2024-04-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0017_rename_iscritical_activity_is_critical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='EF',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='ES',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='LF',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='LS',
        ),
        migrations.AddField(
            model_name='task',
            name='EF',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='ES',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='LF',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='LS',
            field=models.FloatField(default=0.0),
        ),
    ]
