# Generated by Django 4.2.11 on 2024-04-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0018_remove_activity_ef_remove_activity_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='EF',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='ES',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='LF',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='LS',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_tasks', to='cpmApp.activity'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_tasks', to='cpmApp.activity'),
        ),
    ]
