# Generated by Django 4.2.11 on 2024-04-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0019_activity_ef_activity_es_activity_lf_activity_ls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slack',
            field=models.FloatField(default=0.0),
        ),
    ]
