# Generated by Django 4.2.11 on 2024-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0022_activity_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tasks',
            field=models.ManyToManyField(related_name='activities', to='cpmApp.task'),
        ),
    ]
