# Generated by Django 4.2.11 on 2024-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmApp', '0023_alter_activity_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
    ]
